---
title: "data_import"
output: github_document
date: "2024-09-17"
---

```{r setup, echo=FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to import data

##improt the FAS Litters CSV
```{r}
#relative path
litters_df = read_csv("data_import_examples/FAS_litters.csv")
```
What's missing in the data

```{r}
litters_df =
  read_csv(
    file = "data_import_examples/FAS_litters.csv",
    na = c("NA", "", "."),
    col_types = cols(
      Group = col_factor()
    )
  )

litters_df = janitor::clean_names(litters_df)
pull(litters_df, gd0_weight)
```

##Import excel file
Import MLB summary data
```{r}
mlb_df = read_excel("data_import_examples/mlb11.xlsx", sheet = "mlb11")
```

## Import SAS data
```{r}
pulse_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")
```

## Never use read.csv
## Never use $

Cleaning
```{r}
names(litters_df)
```
```{r}
litters_df =janitor::clean_names(litters_df)
names(litters_df)
```
## LA 1
read file using relative path
```{r}
pups_df = read_csv("./data_import_examples/FAS_pups.csv")
```


