---
title: "Tidying Data"
output: github_document
date: "2024-09-24"
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
options(tiblle.print_min = 5)
```


```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
pulse_df
```
this need to go from wide to long format
##pivot longer
```{r}
pulse_tidy_df = 
  pulse_df %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) %>% 
  relocate(id, visit)
pulse_tidy_df
```
one more example!
```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".","")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  )
```
##pivot wider
```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post","pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```
pivot wider for human readability
```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time,
    values_from = mean
  )
```


